Django_Project/mysite/books/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'books' #namespaces in Django

urlpatterns = [
    path('', views.IndexView.as_view(), name = 'index' ),
    path('(?P<pk>[0-9]+)/', views.DetailView.as_view(), name = 'detail'),
    path('books/add/',views.BookCreate.as_view(), name = 'book-add'),
]

Django_Project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls'))
]

Django_Project/mysite/books/models.py
from django.db import models
from django.urls import reverse

# Creating table

class Books(models.Model):

    def get_absolute_url(self):
        return reverse('book:detail',kwargs={'pk':self.pk}) #kwargs=keyword arguments

    def __str__(self):
        return self.name + '-' +self.author
 
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    book_image = models.CharField(max_length=1000)
    

Django_Project/mysite/books/views.py
'''
from django.shortcuts import render
from .models import Books
#from django.template import loader
from django.shortcuts import render
from django.http import Http404
# Create your views here.

from django.http import HttpResponse

def index(request):
    all_books = Books.objects.all()
    context = {
        'all_books' : all_books
    }
     
    return render(request,'books/index.html',context)

def detail(request, book_id):
    try:
        book = Books.objects.get(id=book_id)
    except Books.DoesNotExist:
        raise Http404('This book does not exist')
    return render(request,'books/detail.html',{'book':book})
    '''

#============= Using GENERIC VIEWS==========================
from django.views import generic
from .models import Books
from django.views.generic.edit import CreateView

class IndexView(generic.ListView):
    template_name = 'books/index.html'

    def get_queryset(self):
        return Books.objects.all()

class BookCreate(CreateView):
    model = Books
    fields = ['name','author','price','type','book_image']

class DetailView(generic.DetailView):
    model = Books
    template_name = 'books/detail.html'

Django_Project/mysite/books/templates/books/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href = {% static 'books/style.css' %}>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'books:index' %}">The Bookstore</a>
                <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'books:index' %}">
                            <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'books:book-add' %}">
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add Book
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'books:index' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
            </div>
    </nav>
    {% block body%}
    {% endblock %}
</body>


</html>

Django_Project/mysite/books/templates/books/book_form.html
{% extends 'books/base.html' %}

{% block body %}
<div class="container-fluid">
        <div class="row">
           <div class="col-sm-12 col-md-7">
              <div class="panel panel-default">
                 <div class="panel-body">
      
                         <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'books/book_template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
 
                    </div>
                </div>
            </div>
        </div>
</div>

{% endblock %}

Django_Project/mysite/books/templates/books/book_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">
                {{field.errors}}
            </span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

Django_Project/mysite/books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block body %}

<h1>Book Name:{{book.name}}</h1>
<h2>Author : {{book.author}}</h2>

{% endblock %}

Django_Project/mysite/books/templates/books/index.html
{% extends 'books/base.html' %}
{% block body %}

<html>
    <head>
    </head>
<body>
    <ul>
        {% for book in object_list %}
            <li><a href= "{% url 'books:detail' book.id %}"> {{book.name}} </a> </li>
            <img src="{{book.book_image}}">
        {% endfor %} 
    </ul>
    </body>
</html>
{% endblock %}